name: first-action
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: "shivammathur/setup-php@v2"
        with:
          php-version: "latest"
    - uses: "ramsey/composer-install@v2"
    - run: make lint
    - run: make test-coverage