name: first-action
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: MilesChou/composer-action@master
      with:
        args: install
    - run: make install
    - run: make lint
    - run: make test-coverage